### PR TITLE
Restored activities notification, hoping Gmail won't reject too many mails sent.

### PR DESCRIPTION
**Pull request by clacote**

### CODE REVIEW

**Comment by mpetitdant** [comment]
In https://support.google.com/a/answer/166852?hl=en it is stated 2,000 mails over a rolling 24-hour period. 
To me our bigger numbers are : 
- On mondays we send 1326 (# of members) emails for the weekly newsletter. 
   - We could trick our system to start the batch on sunday 23h59 and send half on sunday, half on monday). 
   - We could limit the members to be notified to the active members ?
- Then around 10 emails per talk comment.

**Comment by clacote** [comment]
Where do your stats come from, like "1324 weekly mails on monday"? Is it the number of members?
Limit to active members is a good choice, like "having done an activity since less than two years". I'll count how many members that is.

**Comment by clacote** [comment]
`select count(distinct member_id) from activity WHERE at > (current_date() - INTERVAL 2 YEAR)` is **1184**.
`select count(distinct member_id) from activity WHERE at > (current_date() - INTERVAL 1 YEAR)` is **805**.

**Comment by mpetitdant** [comment]
Yes in CRUD admin.

**Comment by mpetitdant** [comment]
So 1 year seems good ?

**Pull request merged**
