### PR TITLE
hide the presence by half day since we already know that and took it int...

### PR DESCRIPTION
**Pull request by mpetitdant**
...o account in the planning.

### CODE REVIEW

**Comment by clacote** [comment]
But wasn't a purpose of this form to collect speaker's unavailabilities that would conflict with our proposed planning? I don't see why their availabilities are useless?

**Comment by mpetitdant** [comment]
Because half of the already provided their constraints by mail. So I imagine that if we publish this ability we will have to deal with a new buch of constraints to handle and our planning is almost finished.
That will be for next year (and will be ready in advance :-)

**Comment by mpetitdant** [comment]
Plus the mail based constraints may not be re-filled and if it is the case we will be completely lost ...

**Comment by clacote** [comment]
You might be right. But what about the other half that provided no feedback? It would be a shame to have to explain to speakers : please fill your contraints on this page, but if you have unavailabilities  against our planning, please shoot an email.

**Comment by mpetitdant** [comment]
To be continued aroud a coffee then :-)
The key point being : we should already have their constraints 4 weeks
before the event.

**Comment by mpetitdant** [comment]
Added current validated sessions planned times as a reminder.

**Comment by mpetitdant** [comment]
Plus button on home page to remind speakers to fille their preferences

**Comment by mpetitdant** [comment]
fixes #356

**Comment by clacote** [comment]
Beside my regrets that landing page becomes bloated, that's is OK.

**Pull request merged**
