### PR TITLE
fix api calls and circular references on json serialization

### PR DESCRIPTION
**Pull request by javamind**

### CODE REVIEW

**Comment by clacote** [comment]
I'll check this. But that can't fix the tracked bug which is about members serialization.

**Comment by javamind** [comment]
On my local machine it does..
I know it's weird

**Comment by clacote** [comment]
A fix pushed to javamind/linkit#1

**Comment by clacote** [comment]
I don't understand how this could fix anything. But as soon as you'll merge javamind/linkit#1 if you're OK with it, I'll deploy this to test in prod.

**Comment by javamind** [comment]
Merged you can deploy

**Comment by clacote** [comment]
@javamind hmm... You didn't merge my PR javamind/linkit#1 into your branch, you just merged this PR into master...

**Comment by javamind** [comment]
oups....

**Comment by javamind** [comment]
@clacote  Why have you created a new branch with just one part of my modifications ?

**Comment by clacote** [comment]
@javamind What do you mean? I've just fixed a bug on top of your own branch "fix/apicalls". If you had merged it, that would have fixed it on your branch, updated this PR, which we could have merged with your code and that proposed fix.

**Comment by clacote** [comment]
@javamind nervermind, I'm gonna make a PR to this repository, as you are visibly lost in branches. Are you OK with the code in javamind/linkit#1?

**Comment by javamind** [comment]
yes ok I understood what do you mean... The monday morning is difficult for me :smile: 
What do you want to do now ? A revert on my merge ?

**Comment by clacote** [comment]
No, I'll deal with merge thanks to my git-fu, as soon as you are OK with my proposed code in javamind/linkit#1.

**Comment by javamind** [comment]
It's ok with me

**Comment by clacote** [comment]
That is now deployed.
As expected, that didn't fixed issue #351 : http://www.mix-it.fr/api/members/sponsors is still crashing

**Comment by javamind** [comment]
agggghhhhhhhhhh 
So I haven't the same behavior on localhost

**Comment by clacote** [comment]
Don't you want to apply your same refactoring, as inapprehensible it is, to `ApiMembers` controller?

**Comment by javamind** [comment]
Yes I'll do that

**Pull request merged**
